# Generated by Django 4.2.2 on 2023-07-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='departure_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
