# Generated by Django 4.2.2 on 2023-07-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0005_alter_attendance_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время прихода'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='departure_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время ухода'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.shift', verbose_name='Смена'),
        ),
    ]
