# Generated by Django 4.2.2 on 2023-07-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0006_alter_attendance_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='weekly_report',
            field=models.JSONField(blank=True, null=True, verbose_name='Еженедельный отчет'),
        ),
    ]
